QT.wayland_egl_compositor_hw_integration_private.VERSION = 6.2.0
QT.wayland_egl_compositor_hw_integration_private.name = QtWaylandEglCompositorHwIntegration
QT.wayland_egl_compositor_hw_integration_private.module = Qt6WaylandEglCompositorHwIntegration
QT.wayland_egl_compositor_hw_integration_private.libs = $$QT_MODULE_LIB_BASE
QT.wayland_egl_compositor_hw_integration_private.ldflags = 
QT.wayland_egl_compositor_hw_integration_private.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/QtWaylandEglCompositorHwIntegration $$QT_MODULE_INCLUDE_BASE/QtWaylandEglCompositorHwIntegration/6.2.0 $$QT_MODULE_INCLUDE_BASE/QtWaylandEglCompositorHwIntegration/6.2.0/QtWaylandEglCompositorHwIntegration
QT.wayland_egl_compositor_hw_integration_private.frameworks = 
QT.wayland_egl_compositor_hw_integration_private.bins = $$QT_MODULE_BIN_BASE
QT.wayland_egl_compositor_hw_integration_private.depends =  core gui waylandcompositor_private
QT.wayland_egl_compositor_hw_integration_private.uses = 
QT.wayland_egl_compositor_hw_integration_private.module_config = v2 internal_module
QT.wayland_egl_compositor_hw_integration_private.DEFINES = QT_WAYLAND_EGL_COMPOSITOR_HW_INTEGRATION_LIB
QT.wayland_egl_compositor_hw_integration_private.enabled_features = 
QT.wayland_egl_compositor_hw_integration_private.disabled_features = 
QT_CONFIG += 
QT_MODULES += wayland_egl_compositor_hw_integration_private

