QT.wayland_egl_client_hw_integration_private.VERSION = 6.2.0
QT.wayland_egl_client_hw_integration_private.name = QtWaylandEglClientHwIntegration
QT.wayland_egl_client_hw_integration_private.module = Qt6WaylandEglClientHwIntegration
QT.wayland_egl_client_hw_integration_private.libs = $$QT_MODULE_LIB_BASE
QT.wayland_egl_client_hw_integration_private.ldflags = 
QT.wayland_egl_client_hw_integration_private.includes = $$QT_MODULE_INCLUDE_BASE $$QT_MODULE_INCLUDE_BASE/QtWaylandEglClientHwIntegration $$QT_MODULE_INCLUDE_BASE/QtWaylandEglClientHwIntegration/6.2.0 $$QT_MODULE_INCLUDE_BASE/QtWaylandEglClientHwIntegration/6.2.0/QtWaylandEglClientHwIntegration
QT.wayland_egl_client_hw_integration_private.frameworks = 
QT.wayland_egl_client_hw_integration_private.bins = $$QT_MODULE_BIN_BASE
QT.wayland_egl_client_hw_integration_private.depends =  core gui opengl_private waylandclient_private
QT.wayland_egl_client_hw_integration_private.uses = wayland-client wayland-egl
QT.wayland_egl_client_hw_integration_private.module_config = v2 internal_module
QT.wayland_egl_client_hw_integration_private.DEFINES = QT_WAYLAND_EGL_CLIENT_HW_INTEGRATION_LIB
QT.wayland_egl_client_hw_integration_private.enabled_features = 
QT.wayland_egl_client_hw_integration_private.disabled_features = 
QT_CONFIG += 
QT_MODULES += wayland_egl_client_hw_integration_private

