/* This file was generated by syncqt. */
#ifndef QT_QTDESIGNER_VERSION_H
#define QT_QTDESIGNER_VERSION_H

#define QTDESIGNER_VERSION_STR "6.2.0"

#define QTDESIGNER_VERSION 0x060200

#endif // QT_QTDESIGNER_VERSION_H
